# Generated by Django 4.2.4 on 2023-08-24 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(choices=[('', 'Select Speciality'), ('Dermatology', 'Dermatology'), ('Padiatric', 'Padiatric'), ('Dentist', 'Dentist'), ('Neuro Surgeon', 'Neuro Surgeon'), ('Neurologist', 'Neurologist')], max_length=100, verbose_name='Required Speciality')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Appointment Date and Time')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_attended', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
